name: MacOS

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: configure
        run: cmake -Bbuild -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION

      - name: build
        run: cmake --build build --config $BUILD_TYPE -j4

      - name: test
        run: |
          cd build
          ctest -C $BUILD_TYPE -VV
      
      - name: install project
        run: cmake --build build --target install --config $BUILD_TYPE 
